Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,6 +18,15 @@ jobs:
           rclone_config: ${{ secrets.RCLONE_CONFIG }}
           token: ${{ secrets.GH_PAT }}
 
+      - name: Backup Nextcloud
+        run: |
+          echo "Backing up Nextcloud to backups"
+          rclone sync -P --metadata --create-empty-src-dirs ${{ secrets.NEXTCLOUD_SOURCE }} ${{ secrets.BACKUPS_DEST }}/nextcloud
+          if [ $? -ne 0 ]; then
+            echo "Error backing up nextcloud to backups"
+            exit 1
+          fi
+      
       - name: Backup Immich
         run: |
           echo "Backing up Immich to backups"
@@ -27,12 +36,12 @@ jobs:
             exit 1
           fi
 
-      - name: Backup Nextcloud
+      - name: Sync Backup Folders
         run: |
-          echo "Backing up Nextcloud to backups"
-          rclone sync -P --metadata --create-empty-src-dirs ${{ secrets.NEXTCLOUD_SOURCE }} ${{ secrets.BACKUPS_DEST }}/nextcloud
+          echo "Synching /backups with onedrive-isel/backups"
+          rclone sync -P --metadata --create-empty-src-dirs ${{ secrets.BACKUPS_DEST }} ${{ secrets.ONEDRIVE_DEST }}/backups --exclude"backups/immich/library/upload"
           if [ $? -ne 0 ]; then
-            echo "Error backing up nextcloud to backups"
+            echo "Error synching backup folders"
             exit 1
           fi
 
