Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,27 +28,25 @@ jobs:
           fi
 
           echo "Backing up Immich to backups"
-          rclone sync -P --metadata --create-empty-src-dirs ${{ secrets.IMMICH_SOURCE }} ${{ secrets.BACKUPS_DEST }}/Backups/immich
+          rclone sync -P --metadata --create-empty-src-dirs ${{ secrets.IMMICH_SOURCE }} ${{ secrets.BACKUPS_DEST }}/immich
           if [ $? -ne 0 ]; then
             echo "Error backing up immich to backups"
             exit 1
           fi
 
-          
-
       - name: Backup Nextcloud
         run: |
-          echo "Backing up Nextcloud to backups"
-          rclone sync -P --metadata --create-empty-src-dirs ${{ secrets.NEXTCLOUD_SOURCE }} ${{ secrets.BACKUPS_DEST }}/Backups/nextcloud
-          if [ $? -ne 0 ]; then
-            echo "Error backing up nextcloud to backups"
-            exit 1
-          fi
-
           echo "Backing up Nextcloud to onedrive-isel"
           rclone sync -P --metadata --create-empty-src-dirs ${{ secrets.NEXTCLOUD_SOURCE }} ${{ secrets.ONEDRIVE_DEST }}/Backups/nextcloud
           if [ $? -ne 0 ]; then
             echo "Error backing up nextcloud to onedrive-isel"
+            exit 1
+          fi
+
+          echo "Backing up Nextcloud to backups"
+          rclone sync -P --metadata --create-empty-src-dirs ${{ secrets.NEXTCLOUD_SOURCE }} ${{ secrets.BACKUPS_DEST }}/nextcloud
+          if [ $? -ne 0 ]; then
+            echo "Error backing up nextcloud to backups"
             exit 1
           fi
 
